### ISSUE TITLE
Add not invented here principle

### ISSUE THREAD

**Issue by iluwatar** [webpro/programming-principles#21]
https://en.wikipedia.org/wiki/Not_invented_here

**Comment by webpro** [comment]
Please open a PR if you still like this merged in.

Thanks for the suggestions, @iluwatar. However, to me, this repo isn't a list containing all the programming principles and design patterns that exist, but rather a curated list with the patterns that are important to myself. However, I'm definitely open to reviewing PRs that contain additional design patterns for me to consider!
