### ISSUE TITLE
Question about usage of this resource (License)

### ISSUE THREAD

**Issue by markusmo3** [webpro/programming-principles#8]
Hello there!

I am the web-developer of [iluwatar/java-design-patterns](https://github.com/iluwatar/java-design-patterns) and here to ask about how this resource can and should be used. aka a License of some sorts, because none is given in this and your website repository

I think design patterns and design principles go hand in hand and we'd be happy if we could use and display your work directly on [our website](http://java-design-patterns.com/).

Direct embedding (this repo as a git submodule and jekyll) with information about the author and source repository would be my favorite way of doing exactly that, but that can be debated.

**Comment by webpro** [comment]
Hi @markusmo3, thanks for your message. I'm fine with embedding this content directly in your website. Linking back to this resource is appreciated (but it's up to you).

**Comment by markusmo3** [comment]
Thanks! I will write here again when im done, so you can look at the result :smile:

**Comment by markusmo3** [comment]
Hi again @webpro.
I just finished up the changes to incorperate the principles [and committed it.](https://github.com/iluwatar/java-design-patterns/commit/75c96455d7d6a354dcaf7e3e49ded18344a2794b)
You can take a look at it here http://iluwatar.github.io/java-design-patterns/principles/

I hope you don't mind that i added you to our ["people repository"](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/_data/people.yml) so i can reference you properly.
Because with that i attributed the "Principles" page to you (at the bottom of the page)

If anything isnt to your likings just tell me :smiley: 

Thanks again for letting me embed your content, it is very much appreciated!

**Comment by webpro** [comment]
Thanks @markusmo3! I like it, especially the shortcut for me in the people repository ;-)

One minor thing I noticed is the LinkedIn icon linking to my (inactive) personal Twitter account. So you might want to remove it or change the link to https://www.linkedin.com/in/larskappert.

**Comment by markusmo3** [comment]
Whoops, i didnt mean to link to that!
It was a bug in our code, as you can see in the commit, but I fixed it and it works allready.

**Comment by webpro** [comment]
Thanks @markusmo3 :-)
